baseURL = "https://jonaskufner.com"  # oder https://jokufner.github.io/
defaultContentLanguage = "de"
languageCode = "de-de"
title = "Jonas Kufner | M365 & Power Platform | Tutorials | Coaching"
theme = "PaperMod"
pagination.pagerSize = 10
enableRobotsTXT = true
canonifyURLs = true

[params]
  description = "Lösungen & Best Practices rund um Microsoft Power Platform, Dataverse & SharePoint."
  author = "Jonas Kufner"
  ShowReadingTime = true
  ShowPostNavLinks = true
  env = "production"  # sorgt u.a. für Minify & noindex=off
  [params.goatcounter]
    host = "jonaskufnercom.goatcounter.com" # oder eigene GC-Domain
    enable = true                     # einfacher Toggle


[outputs]
  home = ["HTML", "RSS", "JSON"]

[markup]
  [markup.highlight]
    noClasses = false  # bessere Kontrolle über Syntax-Highlighting via CSS
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true

[menu]
  [[menu.main]]
    name = "Home"
    url = "/index.html"
    weight = 10
  [[menu.main]]
    name = "Blog"
    url = "/posts/"
    weight = 20
  [[menu.main]]
    name = "Über mich"
    url = "/about/"
    weight = 30
  [[menu.main]]
    name = "Kontakt"
    url = "/contact/"
    weight = 40
  [[menu.footer]]
    name = "Impressum"
    url = "/impressum"
    weight = 50
  [[menu.footer]]
    name = "Datenschutz"
    url = "/datenschutz"
    weight = 60
  
